name: Ex2 - Social Network

on:
  push:
    branches:
      - main

jobs:

  build-pipeline-tools:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      ## Ignore building executable files that are already in cache ##
          
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            filesverifier
            valgrindverifier
            clearscreen
            printMessage
            printbanner
            CodesToMessages.csv
          key: ${{ runner.os }}-test-files
        
      - name: Build utils
        if: steps.cache.outputs.cache-hit != 'true' 
        run: |
          git clone https://$GH_PAT@github.com/Cyber-Education-Center/ExerciseTests-Utils.git/ utils
          cd utils
          g++ clearscreen.cpp -o clearscreen
          g++ printbanner.cpp -o printbanner 
          g++ printMessage.cpp -o printMessage
          chmod +x clearscreen
          chmod +x printbanner
          chmod +x printMessage
          
          mv clearscreen ..
          mv printbanner ..
          mv printMessage ..
          mv CodesToMessages.csv ..
          cd ..
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
          
      - name: Build files verifier
        if: steps.cache.outputs.cache-hit != 'true' 
        run: |  
          git clone https://$GH_PAT@github.com/Cyber-Education-Center/ExerciseTests-VerifySubmittedFiles.git/ verifysubmittedfiles
          cd verifysubmittedfiles
          go build .
          chmod +x filesverifier
          mv filesverifier ..
          cd ..
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
  
      - name: Build memory verifier 
        if: steps.cache.outputs.cache-hit != 'true'  
        run: |
          git clone https://$GH_PAT@github.com/Cyber-Education-Center/ExerciseTests-ValgrindVarifier.git/ valgrindvarifier
          cd valgrindvarifier
          g++ ValgrindVarifier.cpp -o valgrindverifier
          chmod +x valgrindverifier
          mv valgrindverifier ..
          cd ..
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
  
      - name: Clone exercise test repo
        run: |
          mkdir checkers
          git clone https://$GH_PAT@github.com/Cyber-Education-Center/ExerciseTests-Ex02.git/ ex2
          cd ex2
          mv PreSubmissionChecker.txt ../checkers
          mv PostSubmissionChecker.txt ../checkers
          mv Part1Checker.txt ../checkers
          mv Part2Checker.txt ../checkers
          mv Part3Checker.txt ../checkers
          mv Part4Checker.txt ../checkers
          mv BonusChecker.txt ../checkers
          mv Ex2Part1Test.cpp ../checkers
          mv Ex2Part2Test.cpp ../checkers
          mv Ex2Part3Test.cpp ../checkers
          mv Ex2Part4Test.cpp ../checkers
          mv Ex2BonusTest.cpp ../checkers
          cd ..
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}

      - name: Build Tests
        run: |
          
  
      ## This step stores the executable files in cache ##
      
      - name: Cache compiled files
        if: steps.cache.outputs.cache-hit != 'true' 
        uses: actions/cache@v3
        with:
          path: |
            filesverifier
            valgrindverifier
            clearscreen
            printMessage
            printbanner
            CodesToMessages.csv
          key: ${{ runner.os }}-test-files
          
      - uses: actions/upload-artifact@v3
        with:
          name: pipeline-tools
          path: checkers
            
  verify-submission:

    needs: build-pipeline-tools
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: pipeline-tools
    
    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
         
    - name: Verify submission
      run: |  
        echo "Verifying .gitignore..."
        ./filesverifier PreSubmissionChecker.txt 5
        echo "Gitignore files exists"
        echo "Verifying required VS files..."
        ./filesverifier PreSubmissionChecker.txt 2
        echo "Required VS files ok"
        echo "Verifying files that should not be submitted..."
        ./filesverifier PreSubmissionChecker.txt 4
        echo "Excluded files ok"

  verify-files:

    needs: build-pipeline-tools  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: pipeline-tools

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Verify files
      run: |
        ./clearscreen 50  
        ./printbanner
        ./filesverifier PostSubmissionChecker.txt 1

  compile-part1:

    needs: build-pipeline-tools
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: pipeline-tools

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Verify files
      run: | 
        ./clearscreen 50
        ./printbanner
        echo "Verifying part1 files exist..."
        ./filesverifier Part1Checker.txt 1
        echo "Part 1 - Device --- files ok"
    
    - name: Compile 
      run: |
        echo "Compiling ..."
        cd temp123
        cp -avf . ../
        cd ..
        mkdir test
        g++ Device.cpp Ex2Part1Test.cpp -o exec1
        mv exec1 test
        echo "Ex2 Part 1 compiled successfully"

    - uses: actions/upload-artifact@v3
      with:
        name: exec1-test
        path: test
      
        
  test-part1:
    needs: [compile-part1]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: exec1-test

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 


    - name: Change Test Permissions
      run: |        
        chmod +x exec1
        
    - name: בדיקה ראשונה
      run: |
        ./printbanner
        ./exec1

  compile-part2:

    needs: build-pipeline-tools
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: pipeline-tools

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Verify files
      run: | 
        ./clearscreen 50
        ./printbanner
        echo "Verifying part2 files exist..."
        ./filesverifier Part2Checker.txt 1
        echo "Part 2 - User --- files ok"
    
    - name: Compile 
      run: |
        echo "Compiling ..."
        cd temp123
        cp -avf . ../
        cd ..
        mkdir test
        g++ Device.cpp User.cpp DeviceList.cpp Ex2Part2Test.cpp -o exec2
        mv exec2 test
        echo "Ex2 Part 2 compiled successfully"

    - uses: actions/upload-artifact@v3
      with:
        name: exec2-test
        path: test
      
        
  test-part2:
    needs: [compile-part2]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: exec2-test

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Change Test Permissions
      run: |        
        chmod +x exec2
        
    - name: בדיקה שנייה
      run: |
        ./printbanner
        ./exec2
        
  compile-part3:

    needs: build-pipeline-tools
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: pipeline-tools

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Verify files
      run: | 
        ./clearscreen 50
        ./printbanner
        echo "Verifying part3 files exist..."
        ./filesverifier Part3Checker.txt 1
        echo "Part 3 - Profile --- files ok"
    
    - name: Compile 
      run: |
        echo "Compiling ..."
        cd temp123
        cp -avf . ../
        cd ..
        mkdir test
        g++ Device.cpp User.cpp DeviceList.cpp Profile.cpp Page.cpp UserList.cpp Ex2Part3Test.cpp -o exec3
        mv exec3 test
        echo "Ex2 Part 3 compiled successfully"

    - uses: actions/upload-artifact@v3
      with:
        name: exec3-test
        path: test
      
        
  test-part3:
    needs: [compile-part3]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: exec3-test

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Change Test Permissions
      run: |        
        chmod +x exec3
        
    - name: בדיקה שלישית
      run: |
        ./printbanner
        ./exec3

  compile-part4:

    needs: build-pipeline-tools
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: pipeline-tools

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Verify files
      run: | 
        ./clearscreen 50
        ./printbanner
        echo "Verifying part4 files exist..."
        ./filesverifier Part4Checker.txt 1
        echo "Part 4 - Social Network --- files ok"
    
    - name: Compile 
      run: |
        echo "Compiling ..."
        cd temp123
        cp -avf . ../
        cd ..
        mkdir test
        g++ Device.cpp User.cpp DeviceList.cpp Profile.cpp Page.cpp UserList.cpp ProfileList.cpp SocialNetwork.cpp Ex2Part4Test.cpp -o exec4
        mv exec4 test
        echo "Ex2 Part 4 compiled successfully"

    - uses: actions/upload-artifact@v3
      with:
        name: exec4-test
        path: test
      
        
  test-part4:
    needs: [compile-part4]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: exec4-test

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Change Test Permissions
      run: |        
        chmod +x exec4
        
    - name: בדיקה רביעית
      run: |
        ./printbanner
        ./exec4 4
  
        
  test-part4-memcheck:
    needs: [test-part4]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: exec4-test

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 

    - name: Change Test Permissions
      run: |        
        chmod +x exec4
        
    - name: בדיקת זיכרון רביעית
      run: |
        sudo apt-get install valgrind
        ./clearscreen 50  
        ./printbanner
        echo "Looking for memory leaks..."
        valgrind --leak-check=yes --log-file=valgrind-out.txt ./exec4 4
        ./valgrindverifier valgrind-out.txt

  compile-bonus:

    needs: build-pipeline-tools
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: pipeline-tools

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Verify files
      run: | 
        ./clearscreen 50
        ./printbanner
        echo "Verifying bonus files exist..."
        ./filesverifier BonusChecker.txt 1
        echo "Bonus --- files ok"
    
    - name: Compile 
      run: |
        echo "Compiling ..."
        cd temp123
        cp -avf . ../
        cd ..
        mkdir test
        g++ Device.cpp User.cpp DeviceList.cpp Profile.cpp Page.cpp UserList.cpp Ex2BonusTest.cpp -o execbonus
        mv execbonus test
        echo "Ex2 Bonus compiled successfully"

    - uses: actions/upload-artifact@v3
      with:
        name: execbonus-test
        path: test
      
        
  test-bonus:
    needs: [compile-bonus]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: execbonus-test

    - name: Restore cloned files
      uses: actions/cache@v3
      with:  
        path: |
          filesverifier
          valgrindverifier
          clearscreen
          printMessage
          printbanner
          CodesToMessages.csv
        key: ${{ runner.os }}-test-files 
        restore-keys: |
          ${{ runner.os }}-test-files 
        
    - name: Change Test Permissions
      run: |        
        chmod +x execbonus
        
    - name: בדיקת בונוס
      run: |
        ./printbanner
        ./execbonus
  

  zip-and-send:

    needs: [verify-submission, test-part1, test-part2, test-part3, test-part4, test-part4-memcheck, test-bonus]
    runs-on: ubuntu-latest
    continue-on-error: true  # This line allows the job to continue without failing the workflow if it encounters an error

    steps:
    - uses: actions/checkout@v3
    
    - name: Get env variables
      run: |
        echo "ING_SERVER_URL=$(grep "ING_SERVER_URL=" utils/ING | cut -d '=' -f2)" >> $GITHUB_ENV
        echo "ZIP_TARGET_SERVER=$(grep "ZIP_TARGET_SERVER=" utils/ING | cut -d '=' -f2)" >> $GITHUB_ENV
        
    - name: Zip and send 
      run: |
        # zip and send commands
        curl -X POST -F "file=@loadedFromPipeline.zip" $ING_SERVER_URL/push_project_zip/$CLASS_NAME/$STUDENT_NAME/$PROJECT_NAME/$GITHUB_SHA/$GITHUB_RUN_NUMBER/$MODIFIED_ZIP_TARGET_SERVER
      if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'ING') }}
